Resources:
    UserPool:
          Type: AWS::Cognito::UserPool
          Properties:
            UserPoolName: rules-engine-auth-pool
            Schema:
              - Name: email
                Required: true
                Mutable: true
            Policies:
              PasswordPolicy:
                MinimumLength: 6
            AutoVerifiedAttributes: ["email"]
    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: rules-engine-user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ALLOW_USER_PASSWORD_AUTH"
          - "ALLOW_REFRESH_TOKEN_AUTH"